version: '3'

silent: true

dotenv: ['.envrc']

tasks:
  default:
    cmds:
      - task -l

  db:
    desc: 'connect to db with psql'
    cmds:
      - psql $CASA_DB_DSN

  build:
    desc: 'build the application'
    cmds:
      - go build -ldflags='-s' -o=./bin/casa ./cmd/web/*.go

  run:
    desc: 'build and run the application'
    cmds:
      - task: build
      - CASA_DB_DSN=$CASA_DB_DSN ./bin/casa

  dev:
    desc: 'build run and watch'
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - clear
      - task: run

  clean:
    desc: 'clean build folder'
    cmds:
      - rm -rf bin
